Refactor: Stomp 서버 분리, Message id @GeneratedValue삭제, build.gradle web…
Libienz/Spoot-Taxi-Server pull request #35
Opened 2023-08-09 09:29 UTC by ks0927

…socket삭제

@Libienz 

- 뭉팅이긴 한데 websocket관련 부분 삭제하고
- 삭제하면서 메세지 저장로직을 API로 구현했습니다.    /save-user 와 /save-exit
- 메세지 id필드에서@GeneratedValue삭제했고 
- build.gradle에서 implementation 'org.springframework.boot:spring-boot-starter-websocket'도 삭제했습니다.

소켓서버 레포 팠습니다 확인해주세여
[https://github.com/ks0927/Spoot-Taxi-Socket-Server](url)

2023-08-09 22:16 UTC, Libienz requested changes
수정 바람

2023-08-09 22:16 UTC, Libienz commented on src/main/java/com/capstone/smutaxi/controller/ChatController.java
> +    @PostMapping("/save-user")
엔드 포인트 다음과 같이 수정
- POST api/chat/messages

 - 자원에 대한 동작은 save처럼 리소스 계층에 쓰는 것이 아니라 HTTP method로 말하도록 해야 함
 - 엔드포인트는 자원만을 식별할 수 있도록 할 것.
- 엔드포인트는 계층구조를 유지한 채 리소스의 복수형으로 쓸 것 

기존에 만들어 놓은 api들도 규약이 지멋대로 일텐데 Security 설정 바꾸면서 api 한번 싹 갈 것임 
나름 중요한 수정지점이라고 본인은 판단하는 중

2023-08-09 22:16 UTC, Libienz commented on src/main/java/com/capstone/smutaxi/controller/ChatController.java
> +        return ResponseEntity.ok(sendUserMessage);
SystemMessage든 UserMessage든 어차피 둘다 Message이고 saveMessage를 호출하는데 api가 두개나 필요 없음 
- POST api/chat/messages로 충분하지 않을까?

2023-08-09 22:16 UTC, Libienz commented on src/main/java/com/capstone/smutaxi/controller/ChatController.java
> +        return ResponseEntity.ok(sendUserMessage);
마찬가지로 소켓서버 컨트롤러에서도 send 하나만 만들면 될 듯
- 현재는 save, exit 있던데 sendMessage  메서드 하나 서비스에서 만들고 type에 따라 분기해서 적절히 send하도록 하면 될 듯 
- 아니면 이게 더 좋아보이는데 Message 엔티티에 추상메서드 send 만들고 이걸 상속하는 userMessage와 SystemMessage가 sendMessage 메서드를 오버라이드 하도록 하면 될 듯
- 이렇게 하면 도메인 주도 설계로 갈 수 있고 전략 패턴을 이용하기에 확장에 유연한 대처가 가능함 (서비스 코드 필요 읎겠네)

2023-08-10 02:50 UTC, ks0927 commented on src/main/java/com/capstone/smutaxi/controller/ChatController.java
> +        return ResponseEntity.ok(sendUserMessage);
@Libienz 
https://github.com/Libienz/Spoot-Taxi-Server/blob/6a58df63dc256a11722dcd4c117704bf7c2c8440/src/main/java/com/capstone/smutaxi/controller/ChatController.java#L26

https://github.com/Libienz/Spoot-Taxi-Server/blob/6a58df63dc256a11722dcd4c117704bf7c2c8440/src/main/java/com/capstone/smutaxi/controller/ChatController.java#L32

해당 코드들의 매개변수를 UserMessage 와 SystemMessage 대신 Message로 쓰게 된다면 웹소켓측에서 UserMessage 와 SystemMessage 형식으로 보내도 Message로 저장됩니다. 따라서 명시적으로 나눠 두었습니다. 이걸 해결할수있으면 어떤 방식이 있을까요?

2023-08-10 03:03 UTC, Libienz commented on src/main/java/com/capstone/smutaxi/controller/ChatController.java
> +        return ResponseEntity.ok(sendUserMessage);
소켓서버에서 UserMessage, SystemMessage 형식으로 보내도 api 서버에서 Message로 '선언' 할 수 있을 텐데
만약 그렇지 않다면 LSP를 위반하는 거고 
간단한 얘기임 우리가 List<T> arr = ArrayList<T> 라고 하는 것처럼 가능할 거임

2023-08-10 04:50 UTC, ks0927 commented on src/main/java/com/capstone/smutaxi/controller/ChatController.java
> +        return ResponseEntity.ok(sendUserMessage);
@Libienz 
클래스의 상속 구조에서 부모 클래스를 통해 서브클래스의 인스턴스를 다루는 경우, JSON 직렬화는 기본적으로 부모 클래스의 멤버만 직렬화합니다. 
따라서 Message를 부모로 하는 SystemMessage나 UserMessage 인스턴스를 직렬화할 때, 부모 클래스인 Message의 필드만 직렬화되고 서브클래스에 추가된 필드는 누락되고 있습니다.
쉽게말하면 UserMessage 타입을 보내도 controller의 매개변수가 Message면 Message로만 직렬화되고있다 입니다.

그래서 현재처럼 매개변수를 분리한 상황을 유지 하는게 좋을것 같습니다.

물론 엔드포인트형식 수정은 추후 토의를 통해 진행하겠습니다.

2023-08-10 05:34 UTC, Libienz commented on src/main/java/com/capstone/smutaxi/controller/ChatController.java
> +        return ResponseEntity.ok(sendUserMessage);
그러네 애초에 부모 타입으로 직렬화, 역직렬화를 거치게 되면 상속된 클래스에만 있는 필드들은 생략되어 전송되는 걸로 나도 방금 확인했음. 너 말대로 api는 분리될 수 밖에 없을 것 같다. 우리 서버 리팩토링 하는 기간이 있으니 엔드포인트 수정 같은 것은 그 때 한번에 하는 것으로 하고 우선은 PR을 승인하겠음 👍🏻

2023-08-10 05:35 UTC, Libienz approved these changes

2023-08-10 05:35 UTC, merged

2023-08-10 05:35 UTC, Libienz commented
LGTM 👍🏻 고생해따